### PR TITLE
ci: update checkout actions

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by RobTillaart** [comment]
Q: which problems does this PR solve?

**Comment by RobTillaart** [comment]
> Q: which problems does this PR solve?

In the meantime I understood a new version of GitHub action v3 is available.
==> so I have to update 175 libraries
==> planned for January

**Comment by thijstriemstra** [comment]
> update 175 libraries

ouch! a simple bash script to update actions using a regex sounds like a good idea

**Comment by RobTillaart** [comment]
Patching the files is not the work, used scripts before. However every build (at least a few dozen) must be checked for anomalies. And I like to increase version numbers and update changelog files. 

Currently I am creating a separate changelog file per Repo and add support in the build for RP2040. Takes a few months. But it allows me to check all repos, their state and sometimes fix /add minor things.

**Comment by RobTillaart** [comment]
@thijstriemstra 

```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```

Why limit the tests only for the master branch?

**Comment by thijstriemstra** [comment]
> Why limit the tests only for the master branch?

Not sure, I use this is all my other projects where it works. Reverted the changes.

> 3 workflows awaiting approval 

Maybe you can approve this workflow so it can be tested in this PR.

**Comment by RobTillaart** [comment]
> Maybe you can approve this workflow so it can be tested in this PR.

I will just merge it into this repo, and do some tests if and how it changes behavior.
Most important question is if I create a test branch e.g. test_issue_24 which is not a PR, will it still run all tests.

We will find out coming hour.

**Comment by RobTillaart** [comment]
@thijstriemstra 
See - https://github.com/RobTillaart/PCF8575/actions

LINT did run
BUILD-CI did not run, so it won't work for test branches.
JSON did not run

I will revert the yml files this afternoon as I have an update in the build-CI to be made too.

**Pull request merged**
